version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: plaid
    versions:
    - 8.1.3
    - 8.1.4
    - 8.1.6
    - 8.2.0
  - dependency-name: ejs
    versions:
    - 3.1.5
